public enum BodyVector
{
	LEFT_SHOULDER,
    LEFT_UPPER_ARM,
    LEFT_FORE_ARM,
    RIGHT_SHOULDER,
    RIGHT_UPPER_ARM,
    RIGHT_FORE_ARM,
    SPINE,
    LEFT_THIGH,
    LEFT_CALF,
    RIGHT_THIGH,
    RIGHT_CALF
}